### PR TITLE
fixed tabindex

### PR DESCRIPTION
**Pull request by arieljannai**
Hi,
- I've fixed the tab index, so now you can move between the lines using the tab key. 
- Added underscore to the File menu, so it will work with Alt + F, or Al + F + S to save and such

### CODE REVIEW

**Comment by Toyz** [comment]
Ooo sweet that makes it even better, I think I should add xml preview tab what do you think?

**Comment by arieljannai** [comment]
It can be nice.
I also thought that it would be nice to have the real source language sentence in front on me while translating. Cause now I had to copy it to notepad and look at it (for the longer sentences).
Something like [that](https://scotch.io/tutorials/google-material-design-input-boxes-in-css3) (the first textboxes with name/email) is possible? (The animation is not necessary). Maybe to combine the title with the real text

**Comment by arieljannai** [comment]
I'll do what I suggested :boom:

**Comment by Toyz** [comment]
We could add a textbox that has the original text under the new text?

**Comment by Toyz** [comment]
Check out the update I made I added preview to the current xml

**Comment by arieljannai** [comment]
That's nice! already updated my fork :stuck_out_tongue_winking_eye:

**Pull request merged**
